# Generated by Django 4.2.14 on 2024-07-11 18:01

from django.db import migrations, models
import djongo.models.fields
import users.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50, unique=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=128)),
                ('role', models.CharField(max_length=50)),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('linkedin', models.URLField(blank=True)),
                ('github', models.URLField(blank=True)),
                ('job', models.CharField(max_length=100)),
                ('summary', models.TextField()),
                ('projects', djongo.models.fields.ArrayField(model_container=users.models.Project)),
                ('about', models.TextField()),
                ('skills', djongo.models.fields.JSONField()),
            ],
        ),
    ]
